apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-pipeline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:feitais/guana-test.git' 
    targetRevision: HEAD
    path: 'apps'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mlflow
  syncPolicy:
    # We turn off automated sync temporarily to fix the button loop
    syncOptions:
      - CreateNamespace=true
      - Replace=true # This forces ArgoCD to replace resources instead of updating them




    
     