apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: distributed-kuberay-pipeline
  namespace: argocd
spec:
  project: default
  source:
    # CHANGE THIS to your actual GitHub or GitLab repository link
    repoURL: 'https://github.com/feitais/guana-test.git'
    targetRevision: HEAD
    path: 'apps' # The folder inside your repo where ray-pipeline.yaml is saved
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
