apiVersion: batch/v1
kind: Job
metadata:
  name: python-ml-pipeline-run
  namespace: mlflow
  annotations:
    # This hook tells ArgoCD to delete the old job and run a fresh one every time you sync
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: pipeline
        image: local-python-pipeline:latest
        imagePullPolicy: Never # Forces Kubernetes to use the local image you just built
      restartPolicy: Never
  backoffLimit: 1